const PALETTE = {
  TORQUISE: '#1abc9c',
  EMERALD: '#2ecc71',
  GREE_SEA: '#16a085',
  NEPHRITIS: '#27ae60',
  SUN_FLOWER: '#f1c40f',
  ORANGE: '#f39c12',
  CARROT: '#e67e22',
  PUMPKIN: '#d35400',
  PETER_RIVER: '#3498db',
  BELIZE_HOLE: '#2980b9',
  ALIZARIN: '#e74c3c',
  POMEGRANATE: '#c0392b',
  AMETHYST: '#9b59b6',
  WISTERIA: '#8e44ad',
  WET_ASPHALT: '#34495e',
  MIDNIGHT_BLUE: '#2c3e50',
  ASBESTOS: '#7f8c8d',
  CONCRETE: '#95a5a6',
  SILVER: '#bdc3c7',
  CLOUDS: '#ecf0f1',
};

const COLORS = {
  PRIMARY: PALETTE.MIDNIGHT_BLUE,
  SECONDARY: PALETTE.WET_ASPHALT,
  CONTRAST: PALETTE.CONCRETE,
  LIGHT: PALETTE.SUN_FLOWER,
  TEXT: {
    PRIMARY: PALETTE.CLOUDS,
    SECONDARY: PALETTE.ALIZARIN,
  },
};

export { COLORS };
