const PALETTE = {
  WHITE: '#FFF',
  RED: '#FF0000',
  YELLOW: '#FFF000',
};

const COLORS = {
  PRIMARY: PALETTE.WHITE,
  SECONDARY: PALETTE.RED,
  TEXT: {
    PRIMARY: PALETTE.RED,
    SECONDARY: PALETTE.YELLOW,
  },
};

export { COLORS };
